export const LayoutActionTypes = {
  SET_THEME: 'SET_THEME',
  OPEN_POPUP_MESSAGE: 'OPEN_POPUP_MESSAGE',
  CLOSE_POPUP_MESSAGE: 'CLOSE_POPUP_MESSAGE',
  OPEN_OVERLAY_MESSAGE: 'OPEN_OVERLAY_MESSAGE',
  CLOSE_OVERLAY_MESSAGE: 'CLOSE_OVERLAY_MESSAGE',
}